#publish your docker image to github container registry
name: publish image and scan

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
     - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-world Docker image
        run: |
          docker build . --tag ghcr.io/lacework-community/inline-scanner-with-github-actions:latest
          docker run ghcr.io/lacework-community/inline-scanner-with-github-actions:latest
          docker push ghcr.io/lacework-community/inline-scanner-with-github-actions:latest

  # use lacework vulnerability scanner to scan published image
  test-inline-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/lacework-community/inline-scanner-with-github-actions:latest

      - name: Scan the image
        uses: lacework/lw-scanner-action@v0.7.1
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ghcr.io/lacework-community/inline-scanner-with-github-actions
          IMAGE_TAG: latest

